config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  root 'photos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  validates :description, presence: true
  has_one_attached :insta_image
  validates :insta_image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: { case_sensitive: false }

  def full_name
    [first_name, last_name].join(' ')
  end

  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :first_name, :last_name])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  def index
    @photos = Photo.all
  end

  def show
  end

  def new
    @photo = Photo.new
  end

  def edit
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id

    respond_to do |format|
      if @photo.save
        format.html { redirect_to photos_url, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:description, :user_id, :insta_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/_alerts.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="flex items-center justify-between flex-wrap bg-gray-100 py-3 lg:px-10 px-3 text-gray-700 border-b border-gray-400">
    <div class="flex items-center flex-no-shrink mr-6">
      <%= link_to "Insta-Stimulus-Tailwind", root_path, class:"link text-xl tracking-tight font-semibold" %>
    </div>
    <div class="block lg:hidden">
      <button class="flex items-center px-3 py-2 border rounded text-grey border-gray-500 hover:text-gray-600 hover:border-gray-600">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
      </button>
    </div>
    <div class="w-full block lg:flex-1 lg:flex items-center text-center lg:text-left">
      <div class="lg:flex-grow">
        <%= link_to "Basic Link", "#", class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
        <% if user_signed_in? %>
        <%= link_to "New Upload", new_photo_path, class: "btn btn-default" %>
        <% end %>
      </div>
      <div class="w-full block lg:flex lg:flex-row lg:flex-1 mt-2 lg:mt-0 text-center lg:text-left lg:justify-end items-center">
        <% if user_signed_in? %>
          <%= link_to current_user.full_name, edit_user_registration_path, class:"link text-xl tracking-tight font-semibold lg:mr-2" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class:"btn btn-default mb-2 lg:mr-2 lg:mb-0 block" %>
          <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-default block" %>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaTailwind</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width-device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/alerts' %>
    <%= render 'layouts/navbar' %>
    <main class="lg:px-10 px-4">
      <%= yield %>
    </main>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-6">
    <%= form.label :description, class: "label" %>
    <%= form.text_area :description, class: "input" %>
  </div>

  <div class="mb-6">
    <%= form.label :insta_image, class: "label" %>
    <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-max-file-size="2" data-dropzone-max-files="1">
       <%= form.file_field :insta_image, direct_upload: true, data: { target: "dropzone.input" } %>
    <div class="dropzone-msg dz-message needsclick text-gray-600">
      <h3 class="dropzone-msg-title ml-1">Drag here to upload or click here to browse</h3>
      <span class="dropzone-msg-desc text ml-1">2 MB file size maximum. </span>
    </div>
    </div>
  </div>



  <div class="mb-6">
    <%= form.submit  class: "btn-default btn" %>
  </div>

<% end %>

app/views/photos/edit.html.erb
<div class="max-w-2xl m-auto">
  <h1 class="text-3xl font-bold text-black mb-6">Edit Photo</h1>

  <%= render 'form', photo: @photo %>
</div>

app/views/photos/index.html.erb
<div class="max-w-6xl m-auto">
  <div class="flex items-center justify-between pb-4 mb-4 border-b">
    <h1 class="text-xl font-bold mb-0 uppercase text-gray-500">Photos</h1>
    <%= link_to "New Photo", new_photo_path, class: "btn btn-default" if user_signed_in? %>
  </div>

  <div class="flex flex-wrap items-center justify-between">
  <% @photos.each do |photo| %>
    <article class="border rounded-lg lg:w-1/3 w-full">
      <%= link_to photo do %>
           <%= image_tag photo.insta_image if photo.insta_image.present? %>
      <% end %>
    <div class="p-6">
        <div class="leading-normal text-lg">
          <%= link_to photo.description, photo %>
        </div>

        <% if user_signed_in? && current_user.id == photo.user_id %>
          <div class="my-4">
            <%= link_to 'Edit', edit_photo_path(photo), class: "btn btn-default" %>
            <%= link_to 'Delete', photo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
          </div>
        <% end %>
      </div>
    </article>
    <% end %>
  </div>
</div>

app/views/photos/new.html.erb
<div class="max-w-2xl m-auto">
  <h1 class="text-3xl font-bold text-black mb-6">New Photo</h1>

  <%= render 'form', photo: @photo %>
</div>

app/views/photos/show.html.erb
<div class="max-w-4xl m-auto">
  <%= link_to @photo do %>
    <%= image_tag @photo.insta_image if @photo.insta_image.present? %>
  <% end %>

  <div class="p-6">
    <div class="leading-normal text-lg">
      <%= @photo.description %>
    </div>

    <% if user_signed_in? && current_user.id == @photo.user_id %>
      <div class="my-4">
        <%= link_to 'Edit', edit_photo_path(@photo), class: "btn btn-default" %>
        <%= link_to 'Delete', @photo, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
    </div>
    <% end %>
  </div>
</div>